### ISSUE TITLE
Import into RDS fails with default pipeline

### ISSUE THREAD

**Issue by 4ctobias** [swiftotter/driver#10]
I created a connection.yaml as described in the README, the mysqdump out of the database works, also the creation of the RDS instance works fine.

But the RDS import fails:

[notice] 01/24/20 12:57:57 Successfully connected.
[info] 01/24/20 12:57:57 Database size is less than the free space available on the PHP drive.
[notice] 01/24/20 12:57:57 Initializing sandbox.
[info] 01/24/20 12:57:57 Using RDS instance: driver-upload-b6756a
[info] 01/24/20 12:57:58 Creating RDS instance: driver-upload-b6756a
[notice] 01/24/20 12:57:59 Exporting database from local MySql
[debug] 01/24/20 12:57:59 Local connection string: mysqldump --user="fahrradlager_ebikeoutlet" --password="" --single-transaction --compress --order-by-primary --host=localhost fahrradlager_ebikeoutlet  > /tmp/driver-3d513c.sql
[notice] 01/24/20 12:58:13 Database dump has completed.
[notice] 01/24/20 12:58:14 Importing database into RDS
ERROR 1045 (28000): Access denied for user 'u5f20d781e41f'@'localhost' (using password: YES)
[notice] 01/24/20 12:58:15 Import to RDS completed.
[notice] 01/24/20 12:58:15 Shutting down RDS

**Comment by JosephMaxwell** [comment]
@4ctobias I apologize for the delay here. I just released some new iterations of this, and most everything is improved.

One thing I added was to automatically locate configuration if this is for a Magento 2 site (in the Driver-Magento2 repository).

Ultimately, what's going on here is RDS is probably not spinning up correctly. To get better output, run `php -ddisplay_errors=1 vendor/bin/driver run -vvv`.
