### ISSUE TITLE
symfony/console versions compatibility

### ISSUE THREAD

**Issue by danielozano** [SwiftOtter/Driver#2]
Hi! I'm trying to make this work with Magento 2 (I've also seen your M2 example). But I see some problems.

I don't know if I should report it here, or inside your [M2 repo](https://github.com/SwiftOtter/Driver-Magento2), If you want me to move it there I will do it!

I'm trying to install it in a M2 CE 2.1.10. Installation ends without problem, but when you try to run it `php route/to/bin/driver run`, I get this error: `Class 'Symfony\Component\Console\Style\SymfonyStyle'`

Checking symfony/console repository I see that this class Is added on version >=2.7, and looking at your [composer.json requirements](https://github.com/SwiftOtter/Driver/blob/master/composer.json#L10), you allow it to be installed with versions >=2.6, this along with magento 2 version < 2.2, will end up with a symfony/console version: ~2.3 <2.7. So this class won't be available.

Is it interesting for you to make it usable by lower magento 2 versions?
Do you prefer to restrict the requirements to symfony/console >= 2.7?

Any help I can provide just ask me!
Thanks a lot for your work and your time!

**Comment by JosephMaxwell** [comment]
Thanks for writing this up. I remember that I had some challenges with trying to find a version that works with both M1 and M2, and I believe that was my resolution as M2 used to use an outdated version of the Console.

I would be fine to open up the requirements and see if that works ok. Would you be able to submit a PR?

Thank you for your time.

**Comment by JosephMaxwell** [comment]
I am closing this issue now.
