### ISSUE TITLE
Change of config folders names

### ISSUE THREAD

**Issue by michalbiarda** [swiftotter/driver#29]
Driver config folders should be changed from `config`/`config.d` to `.driver`. This would minimize potential conflicts with other libs included inside vendor folder.

Watchout: This change will require changes in:
- https://github.com/swiftotter/Driver-Magento1/tree/2.0-develop
- https://github.com/swiftotter/Driver-Magento2/tree/3.0-develop

**Comment by prince-swiftotter** [comment]
@michalbiarda Opened above two PRs respectively for both driver Magento 1 and 2 modules as per request in the issue.
