### ISSUE TITLE
Uploading dump to S3 in debug mode

### ISSUE THREAD

**Issue by lbajsarowicz** [swiftotter/driver#52]
```
Database dump has completed.
Importing database into RDS. Please wait... This will take a long time.
<debug>mysql --user=root --password=magento --host=tmp-mysql --port=3306  magento_integration_tests < /tmp/driver-f6d405.sql</debug>
Import to RDS completed.
Beginning reducing table rows from reduce.yaml.
Successfully connected: db via TCP/IP
Exporting database from remote MySql RDS. Please wait... this will take a long time.
Beginning file upload to: s3:///
```

I don't expect dump to be uploaded due to two reasons:
1. S3 is not configured
2. It's debug mode

**Comment by michalbiarda** [comment]
I think that the debug mode created by @JosephMaxwell served different purpose than for what you're using it. It wasn't created for allowing Driver to work without AWS configured. It was created to temporarily allow bypassing time consuming dump processing. I don't want to change this behavior now.

If you don't need to upload dump to S3, you can create your own pipeline in configuration by copy-pasting `build` pipeline, and removing `upload-data-to-s3` command from the copy.

**Comment by lbajsarowicz** [comment]
Thank you for your quick and thorough answer.
This makes the tool vendor-locked to Amazon Cloud.

**Comment by michalbiarda** [comment]
It looks like it does, but it does not. One can configure their own pipelines and write their own commands, completely excluding Amazon Cloud. The system is very elastic.

I do agree, though, that we could add more options out-of-the box in the future :smile:.
